# Generated by Django 5.2.14 on 2026-09-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('core', '0006_remove_classroom_head_teacher_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together={('date', 'student')},
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='employee',
        ),
    ]
