# Generated by Django 6.0 on 2025-12-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_holiday_alter_student_hikvision_id_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi aloqa'),
        ),
    ]
