# Generated by Django 5.2.14 on 2026-09-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_school_last_activity'),
        ('staff', '0003_employee_addition_hours_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom_name',
        ),
        migrations.AddField(
            model_name='classroom',
            name='head_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_class', to='staff.employee', verbose_name='Sinf rahbari'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shift', verbose_name='Smena'),
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classroom'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Sinf nomi'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Smena nomi'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(verbose_name='Boshlanish vaqti'),
        ),
    ]
