# Generated by Django 5.2.14 on 2026-09-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_student_classroom_name_classroom_head_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='head_teacher',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='school',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='school',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
