# Generated by Django 6.0 on 2025-12-08 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('hikvision_id', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('position_type', models.CharField(choices=[('teacher', "O'qituvchi"), ('admin', "Ma'muriyat")], default='teacher', max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stavka')),
                ('teaching_hours', models.FloatField(default=0, verbose_name='Dars soati')),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.school')),
            ],
            options={
                'unique_together': {('school', 'hikvision_id')},
            },
        ),
    ]
