# Generated by Django 6.0 on 2025-12-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hikvision_id',
            field=models.CharField(editable=False, max_length=20, verbose_name='Terminal ID'),
        ),
    ]
