# Generated by Django 5.2.14 on 2026-09-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_employee_hikvision_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='addition_hours',
            field=models.FloatField(default=0, verbose_name="Qo'shimcha dars soati"),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_time',
            field=models.TimeField(default='17:00', verbose_name='Ish tugashi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='pedagogical_load',
            field=models.FloatField(default=0, verbose_name='Pedagogik yuklama'),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_time',
            field=models.TimeField(default='08:00', verbose_name='Ish boshlanishi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='1 soat narxi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hikvision_id',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='teaching_hours',
            field=models.FloatField(default=0, verbose_name="O'quv soati"),
        ),
    ]
